api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "AfterSale thank you"
handle = "aftersale-thank-you"

  [[extensions.targeting]]
  module = "./src/ThankYou.tsx"
  target = "purchase.thank-you.block.render"

  [extensions.capabilities]
  api_access = true
  network_access = false
  block_progress = false
